services:
  - type: web
    name: hangman-game-frontend
    env: node
    buildCommand: cd hangman-game && npm install && npm run build
    startCommand: cd hangman-game && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
    plan: free

  - type: web
    name: hangman-game-backend
    env: node
    buildCommand: cd backend-server && npm install
    startCommand: cd backend-server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        value: 5000
    plan: free
